# Use the official Airflow image
FROM apache/airflow:2.9.2

# Switch to root to install system dependencies if needed
USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Switch back to the airflow user to install Python packages
USER airflow

# Copy the AIRFLOW-SPECIFIC requirements
COPY requirements-airflow.txt /requirements-airflow.txt

# Install the ML packages into the Airflow environment
RUN pip install --no-cache-dir -r /requirements-airflow.txt