x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile.airflow
  environment:
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
    - AIRFLOW__WEBSERVER__SECRET_KEY=this_is_a_very_secure_secret_key_123 
    - MLFLOW_TRACKING_URI=http://mlflow:5000
    - AWS_ACCESS_KEY_ID=admin
    - AWS_SECRET_ACCESS_KEY=password123
    - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
  volumes:
    # This mounts your local folders directly into Airflow so it can read/write your files!
    - ./dags:/opt/airflow/dags
    - ./src:/opt/airflow/src
    - ./data:/opt/airflow/data
    - ./models:/opt/airflow/models
  depends_on:
    postgres:
      condition: service_healthy

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"
    volumes:                                         
      - postgres_data:/var/lib/postgresql/data       
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5

  airflow-init:
    <<: *airflow-common
    command: version
    environment:
      - _AIRFLOW_DB_UPGRADE=True
      - _AIRFLOW_WWW_USER_CREATE=True
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler

  minio:
    image: minio/minio
    ports:
      - "9000:9000" # API Port
      - "9001:9001" # Web UI Port
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
  
  mlflow:
    image: python:3.12-slim
    ports:
      - "5000:5000"
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password123
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
    command: >
      bash -c "pip install mlflow psycopg2-binary boto3 &&
      mlflow server 
      --backend-store-uri postgresql+psycopg2://airflow:airflow@postgres/mlflow 
      --default-artifact-root s3://mlflow-artifacts/ 
      --host 0.0.0.0 
      --port 5000 
      --allowed-hosts localhost,localhost:5000,127.0.0.1,127.0.0.1:5000,mlflow,mlflow:5000"
    depends_on:
      - postgres
      - minio
volumes:                                             
  postgres_data:
  minio_data:

